### ISSUE TITLE
svg-ben elírás

### ISSUE THREAD

**Issue by peterdeak** [pentike/hungarymap#1]
Az svg-ben "jasz-nagykun-szolnok" helyett "bacs-nagykun-szonlon" van írva.

**Comment by pentike** [comment]
Kedves Péter!

Köszönöm a jelzést, javítani fogom mihamarabb.

pentike

**Comment by pentike** [comment]
Kedves Péter!

Javítottam a hibát, mégegyszer köszi!

pentike

2015-05-29 15:58 GMT+02:00 Péntek Gábor pentike@gmail.com:
